#!/bin/bash

python3 -m pip install --user --upgrade setuptools wheel twine
rm -rf bib2doc.egg-info dist build
python3 setup.py sdist bdist_wheel
# TEST: twine upload --repository-url https://test.pypi.org/legacy/ dist/*
python3 -m twine upload dist/*


